### ISSUE TITLE
Issue with Recognizing Input Folder Path in Command

### ISSUE THREAD

**Issue by SilentGene** [zoubohao/Deepurify#3]
Hi Deepurify Team,

I've encountered an issue while using your software. When executing the command:
```bash
$ deepurify clean -i genome_fa -o genome_fa-deepurify --bin_suffix fa --gpu_num 1 --num_threads_per_device 1
```
I received an error message saying “Your input folder is not exist.” even though my input folder exists. 

After spending some time troubleshooting, I found that modifying the input path from `-i genome_fa` to `-i ./genome_fa` resolves the issue and allows the program to run successfully. This behavior seems strange. Not sure why the script cannot handle relative paths correctly.

Additionally, I'd like to suggest a minor correction in the error message for when the program is unable to find the specified folder. It would be more grammatically correct to say, “Your input folder does not exist.”

Hope this can be looked into and fixed. Thank you for your work on this useful tool!

Cheers,
Heyu

**Comment by zoubohao** [comment]
Hi Heyu

We are very appreciative of your suggestions.  Thank you very much. 

The code in this repo is obsolete since we developed a new version of Deepurify, which has a more powerful performance with less time consumption, according to the comments of the reviewers of Nature Machine Intelligence. 

We will follow your advice and fix the errors in this new version.

Lastly, thank you

Bohao

**Comment by SilentGene** [comment]
Hi Bohao,

Thanks for the reply. I'm looking forward to the new version.

Cheers,
Heyu
